import {
  VIDEO_MODERATION_STATUSES,
  VIDEO_PROCESSING_STATUSES,
  VIDEO_PUBLICATION_STATUSES,
  VIDEO_VISIBILITIES,
  type VideoVisibility,
} from "@/config/video";

export const VIDEO_STATUSES = VIDEO_PROCESSING_STATUSES;
export const VIDEO_PUBLICATION_STATUSES_LIST = VIDEO_PUBLICATION_STATUSES;
export const VIDEO_MODERATION_STATUSES_LIST = VIDEO_MODERATION_STATUSES;
export const VIDEO_VISIBILITIES_LIST = VIDEO_VISIBILITIES;

export type { VideoVisibility };

export const MAX_VIDEO_TITLE_LENGTH = 120;
export const MAX_VIDEO_CAPTION_LENGTH = 2000;
